name: 'Lint'
on:
  push:
  pull_request:
    types: ['opened', 'synchronize', 'reopened']

env:
  CARGO_TERM_COLOR: 'always'
  SQLX_VERSION: '^0.7'
  SQLX_FEATURES: 'rustls,postgres'

jobs:
  fmt:
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'dtolnay/rust-toolchain@v1'
        with:
          toolchain: 'stable'
          components: 'rustfmt'
      - run: 'cargo fmt -- --check'

  lint:
    runs-on: 'ubuntu-24.04'
    services:
      postgres:
        image: 'postgres:16'
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'password'
          POSTGRES_DB: 'newsletter'
        ports:
          - '5432:5432'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'dtolnay/rust-toolchain@v1'
        with:
          toolchain: 'stable'
          components: 'clippy'
      - uses: 'Swatinem/rust-cache@v2'
        with:
          key: 'sqlx-${{ env.SQLX_VERSION }}'
      - name: 'Install sqlx-cli'
        run: cargo install sqlx-cli
          --version=${{ env.SQLX_VERSION }}
          --features ${{ env.SQLX_FEATURES }}
          --no-default-features
          --locked
      - name: 'Install psql'
        run: sudo apt-get update && sudo apt-get install postgresql-client -y
      - name: 'Migrate database'
        run: SKIP_DOCKER=true ./scripts/local/init_db.sh
      - run: 'cargo clippy -- -D warnings'
